// src/Page/Page.vue.tsx
import Vue, { VNode } from 'vue'
import IPage from './IPage';

export default abstract class VPage extends Vue implements IPage{
  protected $router:any
  goBack(): void {
    this.$router.go(-1)
  }
  goAdd(): void {
    this.goRoutes('add')
  }
  goEdit(route: string): void {
    this.goRoutes(`${route}/edit`)
  }
  goList(route: string): void {
    this.goRoutes(`${route}`)
  }
  goDetail(route: string): void {
    this.goRoutes(`${route}`)
  }
  goRoutes(route: string): void {
    const {history,push} = this.$router
    push([history.current.path,route].join("/"))
  }
  abstract render():VNode
}

// src/Page/Page.react.tsx
import React, {Component, ReactNode} from 'react';
import IPage, {IRouter, IProps, IState, PK} from './IPage';

export default abstract class RPage<P extends IProps, S extends IState>
  extends Component<P, S>
  implements IPage, IRouter{

  /**
   * 返回到上一步路由
   */
  public goBack(): void {
    const {history} = this.props;
    history.goBack();
  }
  /**
   * 路由跳转到新增列表项
   */
  public goAdd(): void {
    this.goRoutes(`add`);
  }
  /**
   * 路由跳转到列表项修改路由
   * @param {PK} route 当前路由
   */
  goEdit(route: PK): void {
    this.goRoutes(`${route}/edit`);
  }
  /**
   * 路由跳转到列表页
   * @param {string} route 目标路由
   */
  goList(route?: string): void {
    this.goRoutes(`${route}`);
  }
  /**
   * 路由跳转到列表项详情
   * @param {PK} route 目标路由
   */
  goDetail(route: PK): void {
    this.goRoutes(`${route}`);
  }
  /**
   * 跳转到指定路由
   * @param {string} route 目标路由
   */
  goRoutes(route: string): void {
    const {history, match} = this.props;
    history.push(`${match.url}/${route}`);
  }

  abstract componentDidMount(): void;
  abstract render(): ReactNode;
}
